services:
  storybook-snapshots:
    build:
      context: .
      dockerfile: Dockerfile.snapshots
    working_dir: /workspace
    environment:
      - CI=true
      - BASE_URL=
    volumes:
      - ./:/workspace
    command: ["yarn", "test:storybook:snapshots", "--update-snapshots"]
