FROM mcr.microsoft.com/playwright:v1.55.0-jammy

WORKDIR /workspace

RUN corepack enable
RUN corepack prepare yarn@1.22.22 --activate

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

CMD ["yarn", "test:storybook:snapshots", "--update-snapshots"]
